from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path
from typing import Any

from openai import OpenAI, RateLimitError


ROOT = Path(__file__).resolve().parent

SOURCE_FILE = ROOT / "sari_sistem.py"
CANDIDATE_FILE = ROOT / "mavi_aday.json"


PRIMARY_MODEL = (
    os.getenv("OPENAI_MODEL")
    or "gpt-5.6-luna"
).strip()


FALLBACK_MODEL = (
    os.getenv("MAVI_FALLBACK_MODEL")
    or "gpt-5.6-terra"
).strip()


MAX_OUTPUT_TOKENS = 8000


SYSTEM_PROMPT = """
You are MAVİ, the game-evolution engineer in an autonomous software loop.

Your only target is sari_sistem.py, the authoritative game engine.

Do NOT redesign the website.

Do NOT modify:
- HTML
- CSS
- JavaScript
- GitHub workflows
- mavi.py
- kirmizi.py

Every accepted change must affect actual gameplay or progression.

Valid improvements include:
- battle mechanics
- player stats
- enemy behavior
- actions
- resources
- rewards
- progression
- items
- risk/reward systems
- other executable gameplay rules

Cosmetic-only changes are invalid.

Return ONLY one JSON object:

{
  "summary": "short Turkish summary",
  "reason": "why the gameplay improvement matters",
  "file": "sari_sistem.py",
  "content": "COMPLETE replacement source code"
}

Rules:

- content must be the COMPLETE sari_sistem.py file.
- Never return a diff.
- Never return a patch.
- Preserve Game.
- Preserve Player.
- Preserve Battle.
- Preserve GAME_CONFIG.
- Preserve --self-test.
- Preserve --export-web.
- Keep the exporter compatible with the existing browser.
- Do not invent external files.
- Do not invent services.
- Do not invent APIs.
- Do not add browser-only mechanics.
- Do not intentionally weaken tests.
- Do not delete working mechanics without a concrete reason.
- Make ONE small but meaningful gameplay improvement.
- Keep the source executable.
- Keep randomness deterministic and testable through roll when randomness is needed.

The goal is real gameplay evolution, not dashboard evolution.
"""


def extract_json(
    text: str,
) -> dict[str, Any]:

    text = text.strip()

    try:
        value = json.loads(text)

        if isinstance(value, dict):
            return value

    except json.JSONDecodeError:
        pass

    match = re.search(
        r"\{.*\}\s*$",
        text,
        flags=re.DOTALL,
    )

    if match:

        value = json.loads(
            match.group(0)
        )

        if isinstance(value, dict):
            return value

    raise ValueError(
        "Mavi response was not valid JSON."
    )


def rate_limit_is_long_term(
    error: Exception,
) -> bool:

    message = str(error)

    match = re.search(
        r"try again in\s+"
        r"(?:(\d+)h)?"
        r"(?:(\d+)m)?"
        r"(?:(\d+(?:\.\d+)?)s)?",
        message,
        flags=re.IGNORECASE,
    )

    if not match:
        return False

    hours = float(
        match.group(1) or 0
    )

    minutes = float(
        match.group(2) or 0
    )

    seconds = float(
        match.group(3) or 0
    )

    total_seconds = (
        hours * 3600
        + minutes * 60
        + seconds
    )

    return total_seconds > 600


def request_model(
    client: OpenAI,
    model: str,
    prompt: str,
):
      print(
        f"Mavi model: {model}"
    )

    return client.responses.create(
        model=model,

        input=[
            {
                "role": "system",
                "content": SYSTEM_PROMPT,
            },

            {
                "role": "user",
                "content": prompt,
            },
        ],

        reasoning={
            "effort": "minimal",
        },

        max_output_tokens=MAX_OUTPUT_TOKENS,

        store=False,

        prompt_cache_key=(
            "autonom-mavi-sari-v2"
        ),
    )


def main() -> int:

    api_key = os.getenv(
        "OPENAI_API_KEY"
    )

    if not api_key:

        print(
            "HATA: OPENAI_API_KEY bulunamadı.",
            file=sys.stderr,
        )

        return 2


    if not SOURCE_FILE.exists():

        print(
            (
                "HATA: sari_sistem.py "
                "bulunamadı."
            ),
            file=sys.stderr,
        )

        return 2


    current_source = (
        SOURCE_FILE.read_text(
            encoding="utf-8"
        )
    )


    client = OpenAI(
        api_key=api_key
    )


    prompt = f"""
Improve the actual game engine in the current sari_sistem.py.

Make exactly ONE concrete gameplay improvement.

The complete replacement source must remain compatible with:

python sari_sistem.py --self-test

and:

python sari_sistem.py --export-web

The browser reads docs/data.json generated by --export-web.

Do not change the UI.

Do not return a diff.

Return the COMPLETE sari_sistem.py file.

CURRENT sari_sistem.py:

--- BEGIN SOURCE ---

{current_source}

--- END SOURCE ---

Return ONLY the required JSON object.
"""


    models_to_try = [
        PRIMARY_MODEL
    ]


    if (
        FALLBACK_MODEL
        and FALLBACK_MODEL
        != PRIMARY_MODEL
    ):

        models_to_try.append(
            FALLBACK_MODEL
        )


    response = None

    last_error: Exception | None = None


    for model in models_to_try:

        try:

            response = request_model(
                client,
                model,
                prompt,
            )

            break


        except RateLimitError as exc:

            last_error = exc

            print(
                (
                    f"Rate limit: {model}. "
                    "Başka modele geçiliyor."
                ),
                file=sys.stderr,
            )


            if rate_limit_is_long_term(
                exc
            ):

                continue


            continue


        except Exception as exc:

            last_error = exc

            print(
                (
                    f"Mavi API hatası "
                    f"({model}): {exc}"
                ),
                file=sys.stderr,
            )

            return 1


    if response is None:

        print(
            (
                "HATA: Mavi kullanılabilir "
                "bir model ile cevap veremedi."
            ),
            file=sys.stderr,
        )


        if last_error is not None:

            print(
                str(last_error),
                file=sys.stderr,
            )


        return 1


    candidate = extract_json(
        response.output_text
    )


    if (
        candidate.get("file")
        != "sari_sistem.py"
    ):

        raise ValueError(
            "Mavi yanlış dosyayı hedefledi."
        )


    content = candidate.get(
        "content"
    )


    if not isinstance(
        content,
        str,
    ):

        raise ValueError(
            (
                "Mavi geçerli source "
                "code üretmedi."
            )
        )


    content = content.strip()


    if len(content) < 300:

        raise ValueError(
            (
                "Mavi tarafından üretilen "
                "kod çok kısa."
            )
          )
          payload = {
        "model": getattr(
            response,
            "model",
            PRIMARY_MODEL,
        ),

        "summary": str(
            candidate.get(
                "summary",
                "",
            )
        ).strip(),

        "reason": str(
            candidate.get(
                "reason",
                "",
            )
        ).strip(),

        "file": "sari_sistem.py",

        "content": content,
    }


    CANDIDATE_FILE.write_text(
        json.dumps(
            payload,
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )


    print(
        json.dumps(
            {
                "ok": True,

                "model": payload[
                    "model"
                ],

                "summary": payload[
                    "summary"
                ],
            },

            ensure_ascii=False,
        )
    )


    return 0


if __name__ == "__main__":

    raise SystemExit(
        main()
    )
